# Site settings
title: Imperceptible Thoughts
email:
description: > # this means to ignore newlines until "baseurl:"
  The incoherent, incomprehensible, inconceivable, and incrementally intelligent
  ramblings of John Engelman
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://imperceptiblethoughts.com" # the base hostname & protocol for your site
twitter_username: johnrengelman
github_username:  johnrengelman

# Build settings
markdown: kramdown

kramdown:
  input: GFM

exclude:
  - Gemfile*

gems:
  - jemoji
  - octopress-codefence
  - octopress-solarized
  - octopress-linkblog

google_universal_analytics: UA-321220-4
google_universal_analytics_cookiedomain: auto

linkblog:
  posts:
    marker: ★
